server:
  port: 8585  

eureka:
  client:
    register-with-eureka: true  
    fetch-registry: true
    
    service-url:
      defaultZone:  http://localhost:8761/eureka/


  instance:
    hostname: localhost
    
    
spring:
 application:
  name: API-GATEWAY
  
    
  
  
 cloud:
    gateway:
      routes:
      - id: DOCONNECT-SERVICE                  
        uri: lb://DOCONNECT-SERVICE 
        predicates:
        - Path=/doconnect/**
      
     
      - id:  CHAT-SERVICE                       
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/testchat/**
        
      
